#include <memory>
#include <initializer_list>
#include <unordered_map>
#include <algorithm>
#include <iostream>
#include <vector>
#include <string>
#include <sstream>
#include <fstream>
#include <queue>
#include <stdexcept>
#include <map>
#define DEFINITIONS